export const STATUSES = Object.freeze({ AVAILABLE: "AVAILABLE", EMPTY: "EMPTY", INSUFFICIENT_DATA: "INSUFFICIENT_DATA", UNAVAILABLE: "UNAVAILABLE", ERROR: "ERROR" });

export function safeRate(numerator, denominator) { return denominator > 0 ? numerator / denominator : null; }
export function association(churned, comparison, feature) {
  const c = churned.filter(feature); const r = comparison.filter(feature);
  const result = { churned_count: churned.length, comparison_count: comparison.length, churned_observed: c.length, comparison_observed: r.length, churned_prevalence: safeRate(c.length, churned.length), comparison_prevalence: safeRate(r.length, comparison.length), relative_difference: null };
  if (result.churned_prevalence !== null && result.comparison_prevalence !== null && result.comparison_prevalence !== 0) result.relative_difference = (result.churned_prevalence - result.comparison_prevalence) / result.comparison_prevalence;
  return result;
}
export function sufficiency({ eligible = 0, minimum = 2, configured = true } = {}) { if (!configured) return STATUSES.UNAVAILABLE; if (!eligible) return STATUSES.EMPTY; return eligible >= minimum ? STATUSES.AVAILABLE : STATUSES.INSUFFICIENT_DATA; }
export function summarizeCounts(rows, key) { const counts = new Map(); for (const row of rows) counts.set(row[key] ?? null, (counts.get(row[key] ?? null) || 0) + 1); return [...counts.entries()].map(([value, count]) => ({ value, count })).sort((a, b) => String(a.value).localeCompare(String(b.value))); }
export function journeySummary(instances, minimum = 1) { const eligible = instances.length; const completed = instances.filter((x) => x.status === "COMPLETED").length; const dropped = instances.filter((x) => x.status === "DROPPED_OFF").length; return { status: sufficiency({ eligible, minimum }), eligible, completed, dropped_off: dropped, completion_rate: safeRate(completed, eligible), dropoff_rate: safeRate(dropped, eligible), provenance: { source: "journey_instance" } }; }
export function repeatContactSummary(events, minimum = 1) { const byCustomer = new Map(); for (const event of events.filter((x) => x.c_id)) { const list = byCustomer.get(event.c_id) || []; list.push(event); byCustomer.set(event.c_id, list); } const customers = [...byCustomer.values()]; const repeats = customers.filter((x) => x.length > 1).length; return { status: sufficiency({ eligible: customers.length, minimum }), customers: customers.length, meaningful_contacts: events.length, repeat_customers: repeats, repeat_rate: safeRate(repeats, customers.length), definition: "more than one eligible persisted event per canonical customer" }; }
export function unresolvedSummary(issues, minimum = 1) { const eligible = issues.length; const unresolved = issues.filter((x) => ["OPEN", "IN_PROGRESS", "ESCALATED", "REOPENED"].includes(x.status)); const customers = new Set(unresolved.filter((x) => x.c_id).map((x) => x.c_id)); return { status: sufficiency({ eligible, minimum }), eligible_issues: eligible, unresolved_issues: unresolved.length, unresolved_customers: customers.size, unresolved_rate: safeRate(unresolved.length, eligible) }; }
export function escalationSummary(escalations, minimum = 1) { const total = escalations.length; const structured = escalations.filter((x) => x.detection_method === "STRUCTURED").length; const inferred = escalations.filter((x) => x.detection_method === "INFERRED").length; return { status: sufficiency({ eligible: total, minimum }), total, structured, inferred, customers: new Set(escalations.filter((x) => x.c_id).map((x) => x.c_id)).size }; }
