import PDFDocument from 'pdfkit';
import { Document, HeadingLevel, Packer, Paragraph, Table, TableCell, TableRow } from 'docx';

export type ArtifactFormat = 'json' | 'csv' | 'pdf' | 'docx';
export function safeSlug(value: string) { return value.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 48) || 'company'; }
export function artifactFilename(company: string, reportType: string, runId: string, createdAt: Date, format: ArtifactFormat) { return `breeze-${safeSlug(company)}-${safeSlug(reportType)}-${runId}-${createdAt.toISOString().replace(/[-:]/g, '').replace(/\.\d{3}Z$/, 'Z')}.${format}`; }
const rows = (snapshot: any) => Array.isArray(snapshot?.rows) ? snapshot.rows : [snapshot?.metrics ?? {}];
export function renderJson(snapshot: unknown) { return Buffer.from(JSON.stringify(snapshot, null, 2), 'utf8'); }
export function renderCsv(snapshot: any) { const data: Record<string, unknown>[] = rows(snapshot); const headers: string[] = [...new Set<string>(data.flatMap((row) => Object.keys(row)))].sort(); const encode = (value: unknown) => { if (value == null) return ''; const text = typeof value === 'object' ? JSON.stringify(value) : String(value); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }; return Buffer.from([headers.join(','), ...data.map((row) => headers.map((header) => encode(row[header])).join(','))].join('\n'), 'utf8'); }
export async function renderPdf(snapshot: any) { return await new Promise<Buffer>((resolve, reject) => { const doc = new PDFDocument({ margin: 40 }); const chunks: Buffer[] = []; doc.on('data', (chunk) => chunks.push(Buffer.from(chunk))); doc.on('end', () => resolve(Buffer.concat(chunks))); doc.on('error', reject); doc.fontSize(18).text(snapshot.reportType ?? 'Breeze Report'); doc.moveDown().fontSize(10).text(`Generated: ${snapshot.generatedAt ?? new Date().toISOString()}`); doc.moveDown().text(`Status: ${snapshot.status ?? 'UNKNOWN'}`); doc.moveDown().text(JSON.stringify(snapshot.metrics ?? {}, null, 2)); if (snapshot.limitations?.length) doc.moveDown().text(`Limitations: ${snapshot.limitations.join('; ')}`); doc.end(); }); }
export async function renderDocx(snapshot: any) { const data: Record<string, unknown>[] = rows(snapshot); const headers: string[] = [...new Set<string>(data.flatMap((row) => Object.keys(row)))].sort(); const table = new Table({ rows: [new TableRow({ children: headers.map((header) => new TableCell({ children: [new Paragraph(header)] })) }), ...data.map((row) => new TableRow({ children: headers.map((header) => new TableCell({ children: [new Paragraph(row[header] == null ? '' : String(row[header]))] })) }))] }); const document = new Document({ sections: [{ children: [new Paragraph({ text: String(snapshot.reportType ?? 'Breeze Report'), heading: HeadingLevel.TITLE }), new Paragraph(`Generated: ${snapshot.generatedAt ?? new Date().toISOString()}`), new Paragraph(`Status: ${snapshot.status ?? 'UNKNOWN'}`), table] }] }); return Buffer.from(await Packer.toBuffer(document)); }
export async function renderArtifact(format: ArtifactFormat, snapshot: any) { if (format === 'json') return renderJson(snapshot); if (format === 'csv') return renderCsv(snapshot); if (format === 'pdf') return renderPdf(snapshot); return renderDocx(snapshot); }
