import { and, asc, eq } from 'drizzle-orm';
import { churnOutcome, escalation, event, identityResolution, issue, journeyDefinition, journeyInstance, journeyInstanceStage, journeyStageDefinition } from '../db/schema.js';
import { analyzeChurn } from './churn.js';

export const REPORT_TYPES = ['CUSTOMER_JOURNEY_OVERVIEW', 'DROPOFF_ANALYSIS', 'ESCALATION_ANALYSIS', 'REPEAT_CONTACT_ANALYSIS', 'UNRESOLVED_ISSUES', 'CHURN_ASSOCIATED_EXPERIENCE', 'IDENTITY_DATA_QUALITY'] as const;
export type ReportType = typeof REPORT_TYPES[number];
const result = (reportType: ReportType, status: string, metrics: unknown, rows: unknown[], tables: string[], limitations: string[] = []) => ({ schemaVersion: '1', reportType, status, metrics, rows, generatedAt: new Date().toISOString(), provenance: { tables, formulaVersion: 'prompt-5-v1' }, limitations });

export async function executeReportAnalysis(db: any, companyId: string, reportType: ReportType, parameters: Record<string, unknown>) {
  if (!REPORT_TYPES.includes(reportType)) throw Object.assign(new Error('Unsupported report type'), { code: 'INVALID_INPUT' });
  if (reportType === 'CUSTOMER_JOURNEY_OVERVIEW' || reportType === 'DROPOFF_ANALYSIS') {
    const instances = await db.select({ instance: journeyInstance, definitionName: journeyDefinition.name }).from(journeyInstance).innerJoin(journeyDefinition, eq(journeyInstance.journeyId, journeyDefinition.journeyId)).where(eq(journeyInstance.companyId, companyId)).orderBy(asc(journeyInstance.startedAt));
    const counts = Object.fromEntries(['ACTIVE', 'COMPLETED', 'ABANDONED', 'DROPPED_OFF'].map((status) => [status.toLowerCase(), instances.filter((row: any) => row.instance.status === status).length]));
    if (reportType === 'CUSTOMER_JOURNEY_OVERVIEW') return result(reportType, instances.length ? 'AVAILABLE' : 'EMPTY', { total: instances.length, ...counts }, instances, ['journey_instance', 'journey_definition']);
    const dropped = instances.filter((row: any) => row.instance.status === 'DROPPED_OFF'); return result(reportType, instances.length ? 'AVAILABLE' : 'EMPTY', { eligible: instances.length, dropoffs: dropped.length, rate: instances.length ? dropped.length / instances.length : null }, dropped, ['journey_instance', 'journey_stage_definition'], instances.length ? [] : ['No eligible journey instances.']);
  }
  if (reportType === 'ESCALATION_ANALYSIS') { const rows = await db.select().from(escalation).where(eq(escalation.companyId, companyId)).orderBy(asc(escalation.occurredAt)); const structured = rows.filter((row: any) => row.detectionMethod === 'STRUCTURED').length; return result(reportType, rows.length ? 'AVAILABLE' : 'EMPTY', { total: rows.length, structured, inferred: rows.length - structured, customers: new Set(rows.map((row: any) => row.customerId).filter(Boolean)).size, issues: new Set(rows.map((row: any) => row.issueId).filter(Boolean)).size }, rows, ['escalation']); }
  if (reportType === 'REPEAT_CONTACT_ANALYSIS') { const rows = await db.select({ customerId: event.customerId, eventId: event.eventId, eventTime: event.eventTime, channel: event.channel, eventType: event.eventType }).from(event).where(eq(event.companyId, companyId)).orderBy(asc(event.eventTime)); const grouped = new Map<string, any[]>(); for (const row of rows) if (row.customerId) grouped.set(row.customerId, [...(grouped.get(row.customerId) ?? []), row]); const repeated = [...grouped].filter(([, contacts]) => contacts.length > 1).map(([customerId, contacts]) => ({ customerId, contacts: contacts.length, channels: [...new Set(contacts.map((row) => row.channel).filter(Boolean))] })); return result(reportType, rows.length ? 'AVAILABLE' : 'EMPTY', { eligibleCustomers: grouped.size, repeatContactCustomers: repeated.length, prevalence: grouped.size ? repeated.length / grouped.size : null }, repeated, ['event']); }
  if (reportType === 'UNRESOLVED_ISSUES') { const rows = await db.select().from(issue).where(eq(issue.companyId, companyId)).orderBy(asc(issue.createdAt)); const unresolved = rows.filter((row: any) => ['OPEN', 'IN_PROGRESS', 'ESCALATED', 'REOPENED'].includes(row.status)).map((row: any) => ({ ...row, ageDays: Math.max(0, Math.floor((Date.now() - new Date(row.createdAt).getTime()) / 86400000)) })); return result(reportType, rows.length ? 'AVAILABLE' : 'EMPTY', { eligible: rows.length, unresolved: unresolved.length, prevalence: rows.length ? unresolved.length / rows.length : null, customers: new Set(unresolved.map((row: any) => row.customerId).filter(Boolean)).size }, unresolved, ['issue']); }
  if (reportType === 'CHURN_ASSOCIATED_EXPERIENCE') { const end = parameters.end ? new Date(String(parameters.end)) : new Date(); const start = parameters.start ? new Date(String(parameters.start)) : new Date(end.getTime() - 30 * 86400000); const analysis = await analyzeChurn(db, companyId, start, end); return result(reportType, analysis.status, { sampleSizes: analysis.sampleSizes ?? null, cohorts: analysis.cohorts }, analysis.features ?? [], ['churn_outcome', 'event', 'issue', 'escalation', 'journey_instance'], ['Associations do not establish causation.']); }
  const rows = await db.select().from(identityResolution).where(eq(identityResolution.companyId, companyId)).orderBy(asc(identityResolution.decidedAt)); const counts = Object.fromEntries(['RESOLVED', 'AMBIGUOUS', 'UNRESOLVED'].map((status) => [status.toLowerCase(), rows.filter((row: any) => row.status === status).length])); const events = await db.select({ ingestedAt: event.ingestedAt, processedAt: event.processedAt }).from(event).where(eq(event.companyId, companyId)); const latencies = events.filter((row: any) => row.processedAt && row.ingestedAt).map((row: any) => new Date(row.processedAt).getTime() - new Date(row.ingestedAt).getTime()).filter((value: number) => value >= 0); return result(reportType, rows.length || events.length ? 'AVAILABLE' : 'EMPTY', { totalResolutions: rows.length, ...counts, resolutionRate: rows.length ? (counts.resolved ?? 0) / rows.length : null, averageProcessingLatencyMs: latencies.length ? latencies.reduce((a: number, b: number) => a + b, 0) / latencies.length : null }, rows, ['identity_resolution', 'event']);
}
