CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS company (company_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, timezone text NOT NULL DEFAULT 'UTC', industry text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS data_source (source_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES company(company_id) ON DELETE CASCADE, name text NOT NULL, source_type text NOT NULL, connection_method text NOT NULL, channel text, status text NOT NULL DEFAULT 'NOT_CONFIGURED', credentials_reference text, configuration jsonb NOT NULL DEFAULT '{}', last_sync_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(company_id,name));
CREATE TABLE IF NOT EXISTS source_field_mapping (mapping_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), source_id uuid NOT NULL REFERENCES data_source(source_id) ON DELETE CASCADE, source_field text NOT NULL, semantic_field text NOT NULL, required boolean NOT NULL DEFAULT false, conditional boolean NOT NULL DEFAULT false, validation_status text NOT NULL DEFAULT 'UNMAPPED', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(source_id,source_field,semantic_field));
CREATE TABLE IF NOT EXISTS ingestion_batch (batch_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES company(company_id) ON DELETE CASCADE, source_id uuid NOT NULL REFERENCES data_source(source_id) ON DELETE CASCADE, status text NOT NULL DEFAULT 'RECEIVED', received_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz, total_records integer NOT NULL DEFAULT 0, valid_records integer NOT NULL DEFAULT 0, invalid_records integer NOT NULL DEFAULT 0, errors jsonb NOT NULL DEFAULT '[]');
CREATE TABLE IF NOT EXISTS customer (c_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES company(company_id) ON DELETE CASCADE, display_name text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(company_id,c_id));
CREATE TABLE IF NOT EXISTS identity_mapping (mapping_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES company(company_id) ON DELETE CASCADE, source_id uuid REFERENCES data_source(source_id) ON DELETE CASCADE, identifier_type text NOT NULL, identifier_value text NOT NULL, c_id uuid NOT NULL REFERENCES customer(c_id) ON DELETE CASCADE, valid_from timestamptz, valid_to timestamptz, active boolean NOT NULL DEFAULT true, confidence numeric(5,4) NOT NULL DEFAULT 1, UNIQUE(company_id,source_id,identifier_type,identifier_value));
CREATE TABLE IF NOT EXISTS customer_entity_link (link_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES company(company_id) ON DELETE CASCADE, c_id uuid NOT NULL REFERENCES customer(c_id) ON DELETE CASCADE, entity_type text NOT NULL, entity_id text NOT NULL, valid_from timestamptz, valid_to timestamptz, UNIQUE(company_id,entity_type,entity_id,c_id));
CREATE TABLE IF NOT EXISTS event (event_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES company(company_id) ON DELETE CASCADE, source_id uuid NOT NULL REFERENCES data_source(source_id) ON DELETE CASCADE, source_event_id text, event_fingerprint text, c_id uuid REFERENCES customer(c_id), event_time timestamptz, ingested_at timestamptz NOT NULL DEFAULT now(), processed_at timestamptz, channel text, event_type text, business_entity_type text, business_entity_id text, session_id text, attributes jsonb NOT NULL DEFAULT '{}', raw_payload jsonb NOT NULL DEFAULT '{}', UNIQUE(source_id,source_event_id));
CREATE TABLE IF NOT EXISTS identity_resolution (resolution_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES company(company_id) ON DELETE CASCADE, event_id uuid REFERENCES event(event_id) ON DELETE CASCADE, c_id uuid REFERENCES customer(c_id), status text NOT NULL, method text NOT NULL, confidence numeric(5,4), evidence jsonb NOT NULL DEFAULT '{}', decided_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS journey_definition (journey_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES company(company_id) ON DELETE CASCADE, name text NOT NULL, status text NOT NULL DEFAULT 'DRAFT', configuration jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(company_id,name));
CREATE TABLE IF NOT EXISTS journey_stage_definition (stage_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), journey_id uuid NOT NULL REFERENCES journey_definition(journey_id) ON DELETE CASCADE, stage_key text NOT NULL, name text NOT NULL, ordinal integer NOT NULL, required boolean NOT NULL DEFAULT true, timeout_seconds integer, UNIQUE(journey_id,stage_key));
CREATE TABLE IF NOT EXISTS journey_event_mapping (mapping_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), stage_id uuid NOT NULL REFERENCES journey_stage_definition(stage_id) ON DELETE CASCADE, event_type text NOT NULL, conditions jsonb NOT NULL DEFAULT '{}', UNIQUE(stage_id,event_type));
CREATE TABLE IF NOT EXISTS journey_instance (instance_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES company(company_id) ON DELETE CASCADE, journey_id uuid NOT NULL REFERENCES journey_definition(journey_id) ON DELETE CASCADE, c_id uuid REFERENCES customer(c_id), entity_type text, entity_id text, status text NOT NULL DEFAULT 'ACTIVE', started_at timestamptz, completed_at timestamptz, dropped_off_at timestamptz, dropoff_stage_id uuid REFERENCES journey_stage_definition(stage_id), UNIQUE(journey_id,c_id,entity_type,entity_id));
CREATE TABLE IF NOT EXISTS journey_instance_stage (instance_stage_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), instance_id uuid NOT NULL REFERENCES journey_instance(instance_id) ON DELETE CASCADE, stage_id uuid NOT NULL REFERENCES journey_stage_definition(stage_id) ON DELETE CASCADE, status text NOT NULL DEFAULT 'NOT_REACHED', reached_at timestamptz, completed_at timestamptz, UNIQUE(instance_id,stage_id));
CREATE TABLE IF NOT EXISTS issue (issue_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES company(company_id) ON DELETE CASCADE, c_id uuid REFERENCES customer(c_id), topic text, status text NOT NULL DEFAULT 'OPEN', created_at timestamptz NOT NULL DEFAULT now(), last_contact_at timestamptz, resolved_at timestamptz, resolution_note text, configuration jsonb NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS complaint (complaint_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES company(company_id) ON DELETE CASCADE, issue_id uuid REFERENCES issue(issue_id) ON DELETE SET NULL, c_id uuid REFERENCES customer(c_id), event_id uuid REFERENCES event(event_id) ON DELETE SET NULL, topic text, occurred_at timestamptz NOT NULL, channel text);
CREATE TABLE IF NOT EXISTS escalation (escalation_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES company(company_id) ON DELETE CASCADE, c_id uuid REFERENCES customer(c_id), issue_id uuid REFERENCES issue(issue_id) ON DELETE SET NULL, event_id uuid REFERENCES event(event_id) ON DELETE SET NULL, detection_method text NOT NULL, confidence numeric(5,4), evidence jsonb NOT NULL DEFAULT '{}', occurred_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS churn_outcome (churn_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES company(company_id) ON DELETE CASCADE, c_id uuid NOT NULL REFERENCES customer(c_id) ON DELETE CASCADE, churn_type text NOT NULL, churn_timestamp timestamptz NOT NULL, source text NOT NULL, source_reference text, recorded_reason text, UNIQUE(company_id,c_id,churn_type,churn_timestamp,source));
CREATE TABLE IF NOT EXISTS issue_grouping_rule (rule_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES company(company_id) ON DELETE CASCADE, name text NOT NULL, configuration jsonb NOT NULL DEFAULT '{}', active boolean NOT NULL DEFAULT true, UNIQUE(company_id,name));
CREATE TABLE IF NOT EXISTS report_definition (report_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES company(company_id) ON DELETE CASCADE, name text NOT NULL, description text, report_type text NOT NULL, configuration jsonb NOT NULL DEFAULT '{}', created_by uuid, is_default boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS report_run (run_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), report_id uuid REFERENCES report_definition(report_id) ON DELETE SET NULL, started_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz, status text NOT NULL DEFAULT 'REQUESTED', parameters jsonb NOT NULL DEFAULT '{}', result_snapshot jsonb, artifact_reference jsonb, created_at timestamptz NOT NULL DEFAULT now());

CREATE UNIQUE INDEX IF NOT EXISTS event_source_fingerprint_unique_idx ON event(source_id,event_fingerprint) WHERE event_fingerprint IS NOT NULL; CREATE INDEX IF NOT EXISTS event_company_time_idx ON event(company_id,event_time); CREATE INDEX IF NOT EXISTS event_source_fingerprint_idx ON event(source_id,event_fingerprint); CREATE INDEX IF NOT EXISTS event_company_customer_time_idx ON event(company_id,c_id,event_time); CREATE INDEX IF NOT EXISTS identity_company_identifier_idx ON identity_mapping(company_id,identifier_type,identifier_value); CREATE INDEX IF NOT EXISTS issue_company_status_idx ON issue(company_id,status); CREATE INDEX IF NOT EXISTS journey_instance_company_customer_idx ON journey_instance(company_id,c_id,started_at); CREATE INDEX IF NOT EXISTS escalation_company_time_idx ON escalation(company_id,occurred_at); CREATE INDEX IF NOT EXISTS churn_company_time_idx ON churn_outcome(company_id,churn_timestamp); CREATE INDEX IF NOT EXISTS report_run_report_created_idx ON report_run(report_id,created_at DESC);
