import "dotenv/config";
import express from "express";
import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import pg from "pg";
import { parse as parseCookie, serialize as serializeCookie } from "cookie";
import { executeReport, validateReportParameters } from "./services/reports.js";
import { writeArtifact } from "./services/artifacts.js";
import { GeminiKeyManager, parseGeminiKeys } from "./services/gemini.js";
import { orchestrateToolCall } from "./services/orchestration.js";

const { Pool } = pg;
const app = express();
const pool = process.env.DATABASE_URL ? new Pool({ connectionString: process.env.DATABASE_URL }) : null;
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PORT = Number(process.env.PORT || 8787);
let geminiManager = null;
try { geminiManager = new GeminiKeyManager(parseGeminiKeys(process.env.GEMINI_API_KEYS || "[]")); } catch { geminiManager = null; }

app.use(express.json({ limit: "2mb" }));
app.use(express.raw({ type: ["application/csv", "text/csv", "application/json"], limit: "25mb" }));
app.use((req, res, next) => { res.setHeader("X-Content-Type-Options", "nosniff"); res.setHeader("X-Frame-Options", "DENY"); res.setHeader("Referrer-Policy", "same-origin"); next(); });

const query = async (text, params = []) => { if (!pool) throw Object.assign(new Error("DATABASE_UNAVAILABLE"), { code: "UNAVAILABLE" }); return pool.query(text, params); };
const fail = (res, status, code, message) => res.status(status).json({ error: { code, message } });
const supabaseConfigured = Boolean(process.env.SUPABASE_URL && process.env.SUPABASE_ANON_KEY);
const supabaseRequest = async (pathName, options = {}, admin = false) => {
  if (!supabaseConfigured) throw Object.assign(new Error("SUPABASE_UNAVAILABLE"), { code: "UNAVAILABLE" });
  const headers = { apikey: admin ? process.env.SUPABASE_SERVICE_ROLE_KEY : process.env.SUPABASE_ANON_KEY, "Content-Type": "application/json", ...(options.headers || {}) };
  const response = await fetch(`${process.env.SUPABASE_URL.replace(/\/$/, "")}${pathName}`, { ...options, headers });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw Object.assign(new Error(body.msg || body.message || body.error_description || "SUPABASE_ERROR"), { code: response.status === 429 ? "RETRYABLE" : response.status === 400 ? "INVALID_INPUT" : "UNAUTHORIZED", status: response.status, body });
  return body;
};
const authToken = (req) => parseCookie(req.headers.cookie || "").breeze_access_token || String(req.headers.authorization || "").replace(/^Bearer\s+/i, "") || null;
const auth = async (req, res, next) => { try { const token = authToken(req); if (!token) return fail(res, 401, "UNAUTHORIZED", "Authentication required."); const user = await supabaseRequest("/auth/v1/user", { headers: { Authorization: `Bearer ${token}` } }); const companyId = user.user_metadata?.company_id || user.app_metadata?.company_id; if (!companyId) return fail(res, 403, "UNAUTHORIZED", "Company context is not configured."); req.auth = { providerUserId: user.id, email: user.email, companyId, token }; next(); } catch (error) { return fail(res, error.code === "UNAVAILABLE" ? 503 : 401, error.code === "UNAVAILABLE" ? "UNAVAILABLE" : "UNAUTHORIZED", error.code === "UNAVAILABLE" ? "Authentication service unavailable." : "Authentication required."); } };
const tenant = (req, res, next) => { if (!req.auth?.companyId) return fail(res, 401, "UNAUTHORIZED", "Company context required."); next(); };
const normalize = (value) => String(value || "").trim().toLowerCase();
const uuid = () => crypto.randomUUID();

app.get("/health", (_req, res) => res.json({ ok: true, database: Boolean(pool), service: "breeze-api" }));

app.post("/api/auth/register", async (req, res) => {
  const { companyName, displayName, email, password, timezone = "UTC" } = req.body || {};
  if (!companyName || !displayName || !email || !password || password.length < 12) return fail(res, 400, "INVALID_INPUT", "Company, name, email, and a 12-character password are required.");
  try {
    const signup = await supabaseRequest("/auth/v1/signup", { method: "POST", body: JSON.stringify({ email: normalize(email), password, data: { display_name: displayName.trim() } }) });
    const providerUser = signup.user || signup;
    if (!providerUser?.id) return fail(res, 409, "INVALID_INPUT", "Unable to create this account.");
    const client = await pool.connect();
    try {
      await client.query("BEGIN");
      const company = await client.query("INSERT INTO company(name,timezone) VALUES($1,$2) RETURNING company_id,name,timezone", [companyName.trim(), timezone]);
      await client.query("COMMIT");
      if (!process.env.SUPABASE_SERVICE_ROLE_KEY) return fail(res, 503, "UNAVAILABLE", "Authentication service configuration is incomplete.");
      await supabaseRequest(`/auth/v1/admin/users/${providerUser.id}`, { method: "PUT", body: JSON.stringify({ user_metadata: { display_name: displayName.trim(), company_id: company.rows[0].company_id } }) }, true);
      return res.status(201).json({ account: { email: normalize(email), company: company.rows[0] }, onboarding: { step: 1, readiness: "INCOMPLETE" }, session: signup.access_token ? "ESTABLISHED" : "EMAIL_CONFIRMATION_REQUIRED" });
    } catch (error) { await client.query("ROLLBACK"); if (error.code === "23505") return fail(res, 409, "INVALID_INPUT", "Unable to create this account."); throw error; } finally { client.release(); }
  } catch (error) { return fail(res, error.code === "UNAVAILABLE" ? 503 : 500, error.code === "UNAVAILABLE" ? "UNAVAILABLE" : "INTERNAL_ERROR", error.code === "UNAVAILABLE" ? "Database unavailable." : "Registration failed."); }
});

app.post("/api/auth/login", async (req, res) => {
  const { email, password } = req.body || {}; if (!email || !password) return fail(res, 400, "INVALID_INPUT", "Email and password are required.");
  try { const login = await supabaseRequest("/auth/v1/token?grant_type=password", { method: "POST", body: JSON.stringify({ email: normalize(email), password }) }); const token = login.access_token; const user = await supabaseRequest("/auth/v1/user", { headers: { Authorization: `Bearer ${token}` } }); const companyId = user.user_metadata?.company_id || user.app_metadata?.company_id; if (!companyId) return fail(res, 403, "UNAUTHORIZED", "Company context is not configured."); const company = await query("SELECT company_id,name FROM company WHERE company_id=$1", [companyId]); if (!company.rowCount) return fail(res, 403, "UNAUTHORIZED", "Company context is not configured."); res.setHeader("Set-Cookie", serializeCookie("breeze_access_token", token, { httpOnly: true, sameSite: "lax", secure: process.env.NODE_ENV === "production", maxAge: login.expires_in || 3600, path: "/" })); return res.json({ account: { email: user.email, company: company.rows[0] } }); } catch (error) { return fail(res, error.code === "UNAVAILABLE" ? 503 : 401, error.code === "UNAVAILABLE" ? "UNAVAILABLE" : "UNAUTHORIZED", error.code === "UNAVAILABLE" ? "Authentication service unavailable." : "The email or password is incorrect."); }
});
app.post("/api/auth/logout", auth, async (req, res) => { try { await supabaseRequest("/auth/v1/logout", { method: "POST", headers: { Authorization: `Bearer ${req.auth.token}` } }); } catch {} res.setHeader("Set-Cookie", serializeCookie("breeze_access_token", "", { httpOnly: true, expires: new Date(0), path: "/" })); res.status(204).end(); });
app.get("/api/me", auth, async (req, res) => { const result = await query("SELECT company_id,name,timezone,industry FROM company WHERE company_id=$1", [req.auth.companyId]); res.json({ company: result.rows[0], email: req.auth.email }); });

app.post("/api/onboarding/source", auth, tenant, async (req, res) => { const { name, connectionMethod, sourceType = "EVENT_API", channel, configuration = {} } = req.body || {}; if (!name || !connectionMethod) return fail(res, 400, "INVALID_INPUT", "Source name and connection method are required."); const result = await query("INSERT INTO data_source(company_id,name,source_type,connection_method,channel,status,configuration) VALUES($1,$2,$3,$4,$5,'CONFIGURING',$6) RETURNING source_id,name,connection_method,status", [req.auth.companyId, name.trim(), sourceType, connectionMethod, channel || null, configuration]); res.status(201).json({ source: result.rows[0] }); });
app.get("/api/sources", auth, tenant, async (req, res) => { const result = await query("SELECT source_id,name,source_type,connection_method,channel,status,configuration,last_sync_at,created_at FROM data_source WHERE company_id=$1 ORDER BY created_at ASC", [req.auth.companyId]); res.json({ status: "AVAILABLE", sources: result.rows.map(({ configuration, ...source }) => ({ ...source, configuration: { ...configuration, token: undefined, apiKey: undefined, webhookSecret: undefined, sdkKey: undefined } })) }); });
app.get("/api/sources/:sourceId", auth, tenant, async (req, res) => { const result = await query("SELECT source_id,name,source_type,connection_method,channel,status,configuration,last_sync_at,created_at FROM data_source WHERE company_id=$1 AND source_id=$2", [req.auth.companyId, req.params.sourceId]); if (!result.rowCount) return fail(res, 404, "NOT_FOUND", "Source not found."); const source = result.rows[0]; source.configuration = { ...source.configuration, token: undefined, apiKey: undefined, webhookSecret: undefined, sdkKey: undefined }; res.json({ source }); });
app.patch("/api/sources/:sourceId", auth, tenant, async (req, res) => { const allowed = ["name", "sourceType", "connectionMethod", "channel", "status", "configuration"]; const body = req.body || {}; const fields = Object.keys(body).filter((key) => allowed.includes(key)); if (!fields.length) return fail(res, 400, "INVALID_INPUT", "No supported source fields supplied."); const map = { name: "name", sourceType: "source_type", connectionMethod: "connection_method", channel: "channel", status: "status", configuration: "configuration" }; const values = [req.auth.companyId, req.params.sourceId]; const assignments = fields.map((key, index) => { values.push(body[key]); return `${map[key]}=$${index + 3}`; }); const result = await query(`UPDATE data_source SET ${assignments.join(",")}, created_at=created_at WHERE company_id=$1 AND source_id=$2 RETURNING source_id,name,source_type,connection_method,channel,status`, values); if (!result.rowCount) return fail(res, 404, "NOT_FOUND", "Source not found."); res.json({ source: result.rows[0] }); });
app.post("/api/sources/:sourceId/activate", auth, tenant, async (req, res) => { const result = await query("UPDATE data_source SET status='ACTIVE' WHERE company_id=$1 AND source_id=$2 RETURNING source_id,status", [req.auth.companyId, req.params.sourceId]); if (!result.rowCount) return fail(res, 404, "NOT_FOUND", "Source not found."); res.json({ source: result.rows[0] }); });
app.post("/api/sources/:sourceId/disable", auth, tenant, async (req, res) => { const result = await query("UPDATE data_source SET status='DISABLED' WHERE company_id=$1 AND source_id=$2 RETURNING source_id,status", [req.auth.companyId, req.params.sourceId]); if (!result.rowCount) return fail(res, 404, "NOT_FOUND", "Source not found."); res.json({ source: result.rows[0] }); });
app.post("/api/onboarding/mappings", auth, tenant, async (req, res) => { const { sourceId, mappings = [] } = req.body || {}; if (!sourceId || !Array.isArray(mappings)) return fail(res, 400, "INVALID_INPUT", "Source and mappings are required."); for (const item of mappings) { if (!item.sourceField || !item.semanticField) return fail(res, 400, "INVALID_INPUT", "Each mapping requires sourceField and semanticField."); await query("INSERT INTO source_field_mapping(source_id,source_field,semantic_field,required,conditional,validation_status) VALUES($1,$2,$3,$4,$5,'MAPPED') ON CONFLICT(source_id,source_field,semantic_field) DO UPDATE SET required=EXCLUDED.required,conditional=EXCLUDED.conditional,validation_status='MAPPED'", [sourceId, item.sourceField, item.semanticField, Boolean(item.required), Boolean(item.conditional)]); } res.json({ status: "CONFIGURED", count: mappings.length }); });
app.get("/api/sources/:sourceId/mappings", auth, tenant, async (req, res) => { const source = await query("SELECT source_id FROM data_source WHERE source_id=$1 AND company_id=$2", [req.params.sourceId, req.auth.companyId]); if (!source.rowCount) return fail(res, 404, "NOT_FOUND", "Source not found."); const result = await query("SELECT mapping_id,source_field,semantic_field,required,conditional,validation_status FROM source_field_mapping WHERE source_id=$1 ORDER BY source_field,semantic_field", [req.params.sourceId]); res.json({ status: "AVAILABLE", mappings: result.rows }); });

const insertEvents = async (companyId, sourceId, records) => {
  const batch = await query("INSERT INTO ingestion_batch(company_id,source_id,status,total_records) VALUES($1,$2,'PROCESSING',$3) RETURNING batch_id", [companyId, sourceId, records.length]);
  let accepted = 0; let duplicates = 0; let invalid = 0; const errors = [];
  for (const item of records) {
    const sourceEventId = item.source_event_id || item.id || null; const eventType = item.event_type || item.type || null; const eventTime = item.event_time || item.occurred_at || item.timestamp || null;
    if (!eventType || !eventTime || Number.isNaN(Date.parse(eventTime))) { invalid++; errors.push({ sourceEventId, code: "INVALID_EVENT_TIME_OR_TYPE" }); continue; }
    const fingerprint = crypto.createHash("sha256").update(JSON.stringify({ companyId, sourceId, sourceEventId, eventType, eventTime: new Date(eventTime).toISOString(), channel: item.channel || null, sessionId: item.session_id || null, entity: [item.business_entity_type || null, item.business_entity_id || null] })).digest("hex");
    let customerId = null; const customerReference = item.customer_reference || item.customer_id || item.customerId || null;
    if (customerReference) {
      const existing = await query("SELECT c_id FROM identity_mapping WHERE company_id=$1 AND source_id=$2 AND identifier_type='customer_reference' AND identifier_value=$3 AND active=true LIMIT 2", [companyId, sourceId, String(customerReference)]);
      if (existing.rowCount === 1) customerId = existing.rows[0].c_id;
      else if (!existing.rowCount) { const created = await query("INSERT INTO customer(company_id,display_name) VALUES($1,$2) RETURNING c_id", [companyId, String(customerReference)]); customerId = created.rows[0].c_id; await query("INSERT INTO identity_mapping(company_id,source_id,identifier_type,identifier_value,c_id) VALUES($1,$2,'customer_reference',$3,$4)", [companyId, sourceId, String(customerReference), customerId]); }
    }
    const result = await query("INSERT INTO event(company_id,source_id,source_event_id,event_fingerprint,event_time,processed_at,c_id,session_id,business_entity_type,business_entity_id,channel,event_type,attributes,raw_payload) VALUES($1,$2,$3,$4,$5,now(),$6,$7,$8,$9,$10,$11,$12,$13) ON CONFLICT DO NOTHING RETURNING event_id", [companyId, sourceId, sourceEventId, fingerprint, new Date(eventTime), customerId, item.session_id || null, item.business_entity_type || null, item.business_entity_id || null, item.channel || null, eventType, item.attributes || item, item]);
    if (result.rowCount) {
      accepted++;
      const eventId = result.rows[0].event_id;
      if (customerId) await query("INSERT INTO identity_resolution(company_id,event_id,c_id,status,method,confidence,evidence) VALUES($1,$2,$3,'RESOLVED','SOURCE_IDENTIFIER_MAPPING',1,$4)", [companyId, eventId, customerId, JSON.stringify({ customer_reference: String(customerReference) })]);
      else await query("INSERT INTO identity_resolution(company_id,event_id,status,method,evidence) VALUES($1,$2,'UNRESOLVED','UNRESOLVED',$3)", [companyId, eventId, JSON.stringify({ reason: "No deterministic customer identifier match" })]);
      const topic = item.topic || item.issue_topic || null;
      if (topic && customerId) {
        const openIssue = await query("SELECT issue_id FROM issue WHERE company_id=$1 AND c_id=$2 AND topic=$3 AND status <> 'RESOLVED' ORDER BY created_at DESC LIMIT 1", [companyId, customerId, String(topic)]);
        const issue = openIssue.rowCount ? openIssue.rows[0] : (await query("INSERT INTO issue(company_id,c_id,topic,status,last_contact_at) VALUES($1,$2,$3,'OPEN',$4) RETURNING issue_id", [companyId, customerId, String(topic), new Date(eventTime)])).rows[0];
        await query("INSERT INTO complaint(company_id,issue_id,c_id,event_id,topic,occurred_at,channel) VALUES($1,$2,$3,$4,$5,$6,$7)", [companyId, issue.issue_id, customerId, eventId, String(topic), new Date(eventTime), item.channel || null]);
        await query("UPDATE issue SET last_contact_at=$3 WHERE company_id=$1 AND issue_id=$2", [companyId, issue.issue_id, new Date(eventTime)]);
        if (item.escalation_indicator === true || item.escalated === true || item.event_type === "escalation") await query("INSERT INTO escalation(company_id,c_id,issue_id,event_id,detection_method,confidence,evidence,occurred_at) VALUES($1,$2,$3,$4,'STRUCTURED',1,$5,$6)", [companyId, customerId, issue.issue_id, eventId, JSON.stringify({ field: "escalation_indicator" }), new Date(eventTime)]);
      }
      if (item.churn === true || item.churn_type) await query("INSERT INTO churn_outcome(company_id,c_id,churn_type,churn_timestamp,source,source_reference,recorded_reason) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT DO NOTHING", [companyId, customerId, item.churn_type || "CONFIGURED", new Date(item.churn_timestamp || eventTime), item.churn_source || "STRUCTURED_SOURCE", sourceEventId, item.churn_reason || null]);
    }
    else duplicates++;
  }
  const status = invalid ? (accepted ? "COMPLETED_WITH_ERRORS" : "FAILED") : "COMPLETED";
  await query("UPDATE ingestion_batch SET status=$2,completed_at=now(),valid_records=$3,invalid_records=$4,errors=$5 WHERE batch_id=$1", [batch.rows[0].batch_id, status, accepted, invalid, JSON.stringify(errors)]);
  return { batchId: batch.rows[0].batch_id, status, accepted, duplicates, invalid, received: records.length };
};

app.post("/api/ingest/:sourceId/events", auth, tenant, async (req, res) => { const source = await query("SELECT source_id FROM data_source WHERE source_id=$1 AND company_id=$2 AND status <> 'DISABLED'", [req.params.sourceId, req.auth.companyId]); if (!source.rowCount) return fail(res, 404, "NOT_FOUND", "Source not found."); const records = Array.isArray(req.body) ? req.body : req.body.records; if (!Array.isArray(records)) return fail(res, 400, "INVALID_INPUT", "Expected records array."); try { res.status(202).json(await insertEvents(req.auth.companyId, req.params.sourceId, records)); } catch (error) { return fail(res, 422, "INVALID_INPUT", "One or more records could not be processed."); } });
app.post("/api/webhooks/:sourceId", async (req, res) => { const source = await query("SELECT source_id,company_id,configuration FROM data_source WHERE source_id=$1 AND connection_method='WEBHOOK'", [req.params.sourceId]); if (!source.rowCount) return fail(res, 404, "NOT_FOUND", "Webhook source not found."); const secret = source.rows[0].configuration?.webhookSecret; const signature = req.headers["x-breeze-signature"]; const raw = JSON.stringify(req.body); if (secret && signature !== crypto.createHmac("sha256", secret).update(raw).digest("hex")) return fail(res, 401, "UNAUTHORIZED", "Invalid webhook signature."); const result = await insertEvents(source.rows[0].company_id, req.params.sourceId, Array.isArray(req.body) ? req.body : [req.body]); res.status(202).json(result); });
app.post("/api/sdk/:sourceId/events", async (req, res) => { const source = await query("SELECT source_id,company_id,configuration FROM data_source WHERE source_id=$1 AND connection_method='SDK'", [req.params.sourceId]); if (!source.rowCount) return fail(res, 404, "NOT_FOUND", "SDK source not found."); const key = req.headers["x-breeze-sdk-key"]; if (!key || key !== source.rows[0].configuration?.sdkKey) return fail(res, 401, "UNAUTHORIZED", "Invalid SDK credential."); const result = await insertEvents(source.rows[0].company_id, req.params.sourceId, Array.isArray(req.body) ? req.body : [req.body]); res.status(202).json(result); });

app.get("/api/analytics/overview", auth, tenant, async (req, res) => { const company = req.auth.companyId; const [events, customers, issues] = await Promise.all([query("SELECT count(*)::int AS count FROM event WHERE company_id=$1", [company]), query("SELECT count(*)::int AS count FROM customer WHERE company_id=$1", [company]), query("SELECT count(*)::int AS count FROM issue WHERE company_id=$1 AND status <> 'RESOLVED'", [company])]); res.json({ status: "AVAILABLE", generatedAt: new Date().toISOString(), metrics: { events: events.rows[0].count, customers: customers.rows[0].count, unresolvedIssues: issues.rows[0].count }, provenance: { tables: ["event", "customer", "issue"], companyId: company } }); });
app.get("/api/customers", auth, tenant, async (req, res) => { const limit = bounded(req.query.limit, 100); const result = await query("SELECT c_id,display_name,created_at FROM customer WHERE company_id=$1 ORDER BY created_at ASC,c_id ASC LIMIT $2", [req.auth.companyId, limit]); res.json({ status: result.rowCount ? "AVAILABLE" : "EMPTY", customers: result.rows, limit }); });
app.get("/api/customers/:customerId", auth, tenant, async (req, res) => { const customer = await query("SELECT c_id,display_name,created_at FROM customer WHERE company_id=$1 AND c_id=$2", [req.auth.companyId, req.params.customerId]); if (!customer.rowCount) return fail(res, 404, "NOT_FOUND", "Customer not found."); const [events, issues, journeys, escalations, churn] = await Promise.all([query("SELECT event_id,event_time,event_type,channel,source_id,business_entity_type,business_entity_id,attributes FROM event WHERE company_id=$1 AND c_id=$2 ORDER BY event_time ASC NULLS LAST,event_id ASC", [req.auth.companyId, req.params.customerId]), query("SELECT * FROM issue WHERE company_id=$1 AND c_id=$2 ORDER BY created_at ASC", [req.auth.companyId, req.params.customerId]), query("SELECT ji.*,jd.name AS journey_name FROM journey_instance ji JOIN journey_definition jd ON jd.journey_id=ji.journey_id WHERE ji.company_id=$1 AND ji.c_id=$2 ORDER BY ji.started_at ASC", [req.auth.companyId, req.params.customerId]), query("SELECT * FROM escalation WHERE company_id=$1 AND c_id=$2 ORDER BY occurred_at ASC", [req.auth.companyId, req.params.customerId]), query("SELECT * FROM churn_outcome WHERE company_id=$1 AND c_id=$2 ORDER BY churn_timestamp ASC", [req.auth.companyId, req.params.customerId])]); res.json({ status: "AVAILABLE", customer: customer.rows[0], timeline: events.rows, issues: issues.rows, journeys: journeys.rows, escalations: escalations.rows, churn: churn.rows, provenance: { tables: ["customer", "event", "issue", "journey_instance", "escalation", "churn_outcome"] } }); });
const REPORT_TYPES = ["CUSTOMER_JOURNEY_OVERVIEW", "DROPOFF_ANALYSIS", "ESCALATION_ANALYSIS", "REPEAT_CONTACT_ANALYSIS", "UNRESOLVED_ISSUES", "CHURN_ASSOCIATED_EXPERIENCE", "IDENTITY_DATA_QUALITY"];
app.get("/api/reports", auth, tenant, async (req, res) => { const result = await query("SELECT report_id,name,description,report_type,configuration,is_default,created_at,updated_at FROM report_definition WHERE company_id=$1 ORDER BY created_at ASC", [req.auth.companyId]); res.json({ status: result.rowCount ? "AVAILABLE" : "EMPTY", reports: result.rows }); });
app.post("/api/reports/defaults", auth, tenant, async (req, res) => { const names = { CUSTOMER_JOURNEY_OVERVIEW: "Customer Journey Overview", DROPOFF_ANALYSIS: "Drop-off Analysis", ESCALATION_ANALYSIS: "Escalation Analysis", REPEAT_CONTACT_ANALYSIS: "Repeat Contact Analysis", UNRESOLVED_ISSUES: "Unresolved Issues", CHURN_ASSOCIATED_EXPERIENCE: "Churn-associated Experience Analysis", IDENTITY_DATA_QUALITY: "Identity & Data Quality" }; const created = []; for (const [reportType, name] of Object.entries(names)) { const existing = await query("SELECT report_id FROM report_definition WHERE company_id=$1 AND report_type=$2 AND is_default=true LIMIT 1", [req.auth.companyId, reportType]); if (!existing.rowCount) { const row = await query("INSERT INTO report_definition(company_id,name,report_type,is_default,configuration) VALUES($1,$2,$3,true,'{}') RETURNING report_id,name,report_type", [req.auth.companyId, name, reportType]); created.push(row.rows[0]); } } res.status(201).json({ status: "AVAILABLE", reports: created }); });
app.post("/api/reports", auth, tenant, async (req, res) => { const { name, description = null, reportType, configuration = {}, isDefault = false } = req.body || {}; if (!name || !REPORT_TYPES.includes(reportType)) return fail(res, 400, "INVALID_INPUT", "A supported report name and type are required."); const result = await query("INSERT INTO report_definition(company_id,name,description,report_type,configuration,is_default) VALUES($1,$2,$3,$4,$5,$6) RETURNING *", [req.auth.companyId, name.trim(), description, reportType, configuration, Boolean(isDefault)]); res.status(201).json({ report: result.rows[0] }); });
app.post("/api/reports/:reportId/runs", auth, tenant, async (req, res) => { const definition = await query("SELECT * FROM report_definition WHERE company_id=$1 AND report_id=$2", [req.auth.companyId, req.params.reportId]); if (!definition.rowCount) return fail(res, 404, "NOT_FOUND", "Report not found."); const run = await query("INSERT INTO report_run(report_id,status,parameters) VALUES($1,'RUNNING',$2) RETURNING run_id,report_id,status,started_at", [req.params.reportId, req.body?.parameters || definition.rows[0].configuration]); try { const counts = await query("SELECT count(*)::int AS events,count(DISTINCT c_id)::int AS customers FROM event WHERE company_id=$1", [req.auth.companyId]); const snapshot = { status: "AVAILABLE", report_type: definition.rows[0].report_type, metrics: counts.rows[0], generated_at: new Date().toISOString(), provenance: { tables: ["event"], company_id: req.auth.companyId } }; const completed = await query("UPDATE report_run SET status='COMPLETED',completed_at=now(),result_snapshot=$2 WHERE run_id=$1 RETURNING *", [run.rows[0].run_id, snapshot]); return res.status(201).json({ run: completed.rows[0] }); } catch (error) { await query("UPDATE report_run SET status='FAILED',completed_at=now(),result_snapshot=$2 WHERE run_id=$1", [run.rows[0].run_id, { status: "ERROR", error: "REPORT_EXECUTION_FAILED" }]); return fail(res, 500, "INTERNAL_ERROR", "Report execution failed."); } });
app.delete("/api/reports/:reportId", auth, tenant, async (req, res) => { const result = await query("DELETE FROM report_definition WHERE company_id=$1 AND report_id=$2 RETURNING report_id", [req.auth.companyId, req.params.reportId]); if (!result.rowCount) return fail(res, 404, "NOT_FOUND", "Report not found."); res.status(204).end(); });
app.post("/api/reports/:reportId/execute", auth, tenant, async (req, res) => { const definition = await query("SELECT * FROM report_definition WHERE company_id=$1 AND report_id=$2", [req.auth.companyId, req.params.reportId]); if (!definition.rowCount) return fail(res, 404, "NOT_FOUND", "Report not found."); let parameters; try { parameters = validateReportParameters({ ...(definition.rows[0].configuration || {}), ...(req.body?.parameters || {}), report_type: definition.rows[0].report_type }, "UTC"); } catch (error) { return fail(res, 400, error.code || "INVALID_INPUT", error.message); } const run = await query("INSERT INTO report_run(report_id,status,parameters) VALUES($1,'RUNNING',$2) RETURNING run_id", [req.params.reportId, { ...parameters, company_id: req.auth.companyId }]); try { const snapshot = await executeReport({ reportType: definition.rows[0].report_type, companyId: req.auth.companyId, parameters, query }); const saved = await query("UPDATE report_run SET status='COMPLETED',completed_at=now(),result_snapshot=$2 WHERE run_id=$1 RETURNING *", [run.rows[0].run_id, { ...snapshot, run_id: run.rows[0].run_id }]); res.status(201).json({ run: saved.rows[0] }); } catch (error) { await query("UPDATE report_run SET status='FAILED',completed_at=now(),result_snapshot=$2 WHERE run_id=$1", [run.rows[0].run_id, { status: "ERROR", error: "REPORT_EXECUTION_FAILED" }]); fail(res, 500, "INTERNAL_ERROR", "Report execution failed."); } });
app.post("/api/reports/runs/:runId/artifacts", auth, tenant, async (req, res) => { const format = String(req.body?.format || "json").toLowerCase(); if (!["json", "csv"].includes(format)) return fail(res, 400, "UNAVAILABLE", "PDF and DOCX rendering are not available in this runtime."); const run = await query("SELECT rr.*,rd.report_type, c.name FROM report_run rr JOIN report_definition rd ON rd.report_id=rr.report_id JOIN company c ON c.company_id=rd.company_id WHERE rr.run_id=$1 AND rd.company_id=$2", [req.params.runId, req.auth.companyId]); if (!run.rowCount || run.rows[0].status !== "COMPLETED") return fail(res, 404, "NOT_FOUND", "Completed report run not found."); try { const artifact = await writeArtifact({ directory: path.join(__dirname, "../artifacts"), company: run.rows[0].name, reportType: run.rows[0].report_type, runId: run.rows[0].run_id, format, snapshot: run.rows[0].result_snapshot }); await query("UPDATE report_run SET artifact_reference=$2 WHERE run_id=$1", [req.params.runId, artifact]); res.status(201).json({ artifact }); } catch { fail(res, 500, "INTERNAL_ERROR", "Artifact generation failed."); } });
app.get("/api/reports/runs", auth, tenant, async (req, res) => { const result = await query("SELECT rr.* FROM report_run rr LEFT JOIN report_definition rd ON rd.report_id=rr.report_id WHERE rd.company_id=$1 OR (rd.report_id IS NULL AND rr.parameters->>'company_id'=$1) ORDER BY rr.created_at DESC LIMIT 100", [req.auth.companyId]); res.json({ status: result.rowCount ? "AVAILABLE" : "EMPTY", runs: result.rows }); });

const MCP_TOOLS = new Set(["get_customer_profile", "get_customer_timeline", "get_customer_issues", "get_customer_journeys", "get_customer_escalations", "analyze_journey", "analyze_dropoffs", "analyze_repeat_contacts", "analyze_unresolved_issues", "analyze_escalations", "analyze_churn_associations", "analyze_identity_resolution", "get_data_quality"]);
const mcpResult = (tool, status, data, req, extra = {}) => ({ tool, status, data, period: extra.period || null, timezone: extra.timezone || "UTC", generated_at: new Date().toISOString(), provenance: { tables: extra.tables || [], company_id: req.auth.companyId, freshness: "LIVE" }, ...extra });
const bounded = (value, fallback = 100) => Math.min(Math.max(Number(value) || fallback, 1), 500);
const customerFor = async (companyId, ref) => { const result = await query("SELECT c_id,display_name,created_at FROM customer WHERE company_id=$1 AND (c_id::text=$2 OR display_name=$2) ORDER BY c_id LIMIT 2", [companyId, String(ref || "")]); if (result.rowCount > 1) return { ambiguous: true }; return result.rows[0] || null; };
const mcpHandler = async (tool, req) => {
  const companyId = req.auth.companyId; const input = req.body || {}; const limit = bounded(input.limit); const customer = ["get_customer_profile", "get_customer_timeline", "get_customer_issues", "get_customer_journeys", "get_customer_escalations"].includes(tool) ? await customerFor(companyId, input.customer_ref) : null;
  if (customer?.ambiguous) return mcpResult(tool, "AMBIGUOUS", null, req, { error: { code: "AMBIGUOUS", message: "Customer reference is not unique." } });
  if (customer === null && input.customer_ref) return mcpResult(tool, "NOT_FOUND", null, req, { error: { code: "NOT_FOUND", message: "Customer not found." } });
  if (tool === "get_customer_profile") { const [ids, resolutions] = await Promise.all([query("SELECT identifier_type,identifier_value,source_id,active,confidence FROM identity_mapping WHERE company_id=$1 AND c_id=$2 ORDER BY identifier_type,identifier_value", [companyId, customer.c_id]), query("SELECT status,method,confidence,evidence,decided_at FROM identity_resolution WHERE company_id=$1 AND c_id=$2 ORDER BY decided_at DESC LIMIT 1", [companyId, customer.c_id])]); return mcpResult(tool, "AVAILABLE", { customer, identifiers: ids.rows, identity: resolutions.rows[0] || null }, req, { tables: ["customer", "identity_mapping", "identity_resolution"] }); }
  if (tool === "get_customer_timeline") { const r = await query("SELECT event_id,event_time,event_type,channel,source_id,session_id,business_entity_type,business_entity_id,c_id,attributes FROM event WHERE company_id=$1 AND c_id=$2 ORDER BY event_time ASC NULLS LAST,event_id ASC LIMIT $3", [companyId, customer.c_id, limit]); return mcpResult(tool, r.rowCount ? "AVAILABLE" : "EMPTY", { events: r.rows }, req, { tables: ["event"], limit }); }
  if (tool === "get_customer_issues") { const r = await query("SELECT issue_id,topic,status,created_at,last_contact_at,resolved_at,resolution_note FROM issue WHERE company_id=$1 AND c_id=$2 ORDER BY created_at ASC LIMIT $3", [companyId, customer.c_id, limit]); return mcpResult(tool, r.rowCount ? "AVAILABLE" : "EMPTY", { issues: r.rows }, req, { tables: ["issue", "complaint"], limit }); }
  if (tool === "get_customer_journeys") { const r = await query("SELECT ji.instance_id,ji.status,ji.started_at,ji.completed_at,ji.dropped_off_at,ji.dropoff_stage_id,jd.name FROM journey_instance ji JOIN journey_definition jd ON jd.journey_id=ji.journey_id WHERE ji.company_id=$1 AND ji.c_id=$2 ORDER BY ji.started_at ASC LIMIT $3", [companyId, customer.c_id, limit]); return mcpResult(tool, r.rowCount ? "AVAILABLE" : "EMPTY", { journeys: r.rows }, req, { tables: ["journey_instance", "journey_definition"], limit }); }
  if (tool === "get_customer_escalations") { const r = await query("SELECT escalation_id,issue_id,event_id,detection_method,confidence,evidence,occurred_at FROM escalation WHERE company_id=$1 AND c_id=$2 ORDER BY occurred_at ASC LIMIT $3", [companyId, customer.c_id, limit]); return mcpResult(tool, r.rowCount ? "AVAILABLE" : "EMPTY", { escalations: r.rows }, req, { tables: ["escalation"], limit }); }
  if (tool === "analyze_identity_resolution") { const r = await query("SELECT status,count(*)::int AS count FROM identity_resolution WHERE company_id=$1 GROUP BY status ORDER BY status", [companyId]); const total = r.rows.reduce((n, x) => n + x.count, 0); return mcpResult(tool, total ? "AVAILABLE" : "EMPTY", { counts: r.rows, eligible_events: total, rates: total ? Object.fromEntries(r.rows.map((x) => [x.status, x.count / total])) : null }, req, { tables: ["identity_resolution"] }); }
  if (tool === "get_data_quality") { const r = await query("SELECT count(*)::int AS events,count(*) FILTER (WHERE processed_at IS NOT NULL)::int AS processed,count(*) FILTER (WHERE event_time IS NULL)::int AS missing_event_time,avg(EXTRACT(EPOCH FROM (processed_at-ingested_at))) FILTER (WHERE processed_at IS NOT NULL)::float AS processing_latency_seconds FROM event WHERE company_id=$1", [companyId]); const row = r.rows[0]; return mcpResult(tool, row.events ? "AVAILABLE" : "EMPTY", { ...row }, req, { tables: ["event"] }); }
  if (tool === "analyze_unresolved_issues") { const r = await query("SELECT count(*)::int AS issues,count(DISTINCT c_id)::int AS customers,avg(EXTRACT(EPOCH FROM (now()-created_at))/3600)::float AS average_age_hours FROM issue WHERE company_id=$1 AND status IN ('OPEN','IN_PROGRESS','ESCALATED','REOPENED')", [companyId]); return mcpResult(tool, r.rows[0].issues ? "AVAILABLE" : "EMPTY", r.rows[0], req, { tables: ["issue"] }); }
  if (tool === "analyze_escalations") { const r = await query("SELECT count(*)::int AS total,count(DISTINCT c_id)::int AS customers,count(*) FILTER (WHERE detection_method='STRUCTURED')::int AS structured,count(*) FILTER (WHERE detection_method='INFERRED')::int AS inferred FROM escalation WHERE company_id=$1", [companyId]); return mcpResult(tool, r.rows[0].total ? "AVAILABLE" : "EMPTY", r.rows[0], req, { tables: ["escalation"] }); }
  if (tool === "analyze_repeat_contacts") { const r = await query("SELECT count(*)::int AS contacts,count(DISTINCT c_id)::int AS customers FROM event WHERE company_id=$1 AND c_id IS NOT NULL", [companyId]); return mcpResult(tool, r.rows[0].contacts ? "AVAILABLE" : "EMPTY", { ...r.rows[0], repeat_definition: "meaningful persisted events; same-issue repeats require Issue association" }, req, { tables: ["event", "issue"] }); }
  if (tool === "analyze_journey" || tool === "analyze_dropoffs") { const r = await query("SELECT count(*)::int AS eligible,count(*) FILTER (WHERE status='COMPLETED')::int AS completed,count(*) FILTER (WHERE status='DROPPED_OFF')::int AS dropped_off FROM journey_instance WHERE company_id=$1", [companyId]); const row = r.rows[0]; return mcpResult(tool, row.eligible ? "AVAILABLE" : "EMPTY", { ...row, completion_rate: row.eligible ? row.completed / row.eligible : null, dropoff_rate: row.eligible ? row.dropped_off / row.eligible : null }, req, { tables: ["journey_instance"] }); }
  if (tool === "analyze_churn_associations") { const r = await query("SELECT count(*)::int AS churned FROM churn_outcome WHERE company_id=$1", [companyId]); return mcpResult(tool, r.rows[0].churned ? "INSUFFICIENT_DATA" : "UNAVAILABLE", { churned: r.rows[0].churned, reason: r.rows[0].churned ? "Comparison cohort and feature sufficiency must be evaluated." : "No configured churn source data." }, req, { tables: ["churn_outcome"] }); }
  return mcpResult(tool, "UNAVAILABLE", null, req, { error: { code: "UNAVAILABLE", message: "The configured capability is unavailable." } });
};
app.post("/api/mcp/:tool", auth, tenant, async (req, res) => { if (!MCP_TOOLS.has(req.params.tool)) return fail(res, 404, "NOT_FOUND", "Unknown MCP tool."); try { return res.json(await mcpHandler(req.params.tool, req)); } catch (error) { return fail(res, error.code === "UNAVAILABLE" ? 503 : 500, error.code || "INTERNAL_ERROR", error.code === "UNAVAILABLE" ? "Database unavailable." : "Tool execution failed."); } });
app.post("/api/chat", auth, tenant, async (req, res) => { if (!geminiManager) return fail(res, 503, "UNAVAILABLE", "Gemini is not configured."); const question = String(req.body?.question || "").trim(); if (!question) return fail(res, 400, "INVALID_INPUT", "Question is required."); try { const first = await geminiManager.complete(`Select exactly one approved Breeze MCP tool for this question. Return JSON only with name and arguments. Question: ${question}`); const text = first?.candidates?.[0]?.content?.parts?.map((part) => part.text || "").join("") || ""; const call = JSON.parse(text.match(/\{[\s\S]*\}/)?.[0] || "{}"); const toolResult = await orchestrateToolCall({ call, invoke: (name, args) => mcpHandler(name, { auth: req.auth, body: args }) }); const final = await geminiManager.complete(`Answer the user using only this deterministic Breeze tool result. Preserve unavailable, insufficient, empty, and association language. Question: ${question}\nTool result: ${JSON.stringify(toolResult.result)}`); return res.json({ status: "AVAILABLE", answer: final, tool: toolResult.tool, result: toolResult.result }); } catch (error) { return fail(res, error.code === "UNAVAILABLE" ? 503 : 502, error.code || "ERROR", error.code === "UNAVAILABLE" ? "Gemini is temporarily unavailable." : "Unable to process the question safely."); } });

app.use((error, _req, res, _next) => fail(res, 500, "INTERNAL_ERROR", "Unexpected service failure."));
app.listen(PORT, () => console.log(`Breeze API listening on http://localhost:${PORT}`));
