import { boolean, integer, jsonb, numeric, pgTable, text, timestamp, uuid, unique } from 'drizzle-orm/pg-core';

const id = (name: string) => uuid(name).defaultRandom().primaryKey();
const tenant = (name = 'company_id') => uuid(name).notNull().references(() => company.companyId, { onDelete: 'cascade' });
const created = () => timestamp('created_at', { withTimezone: true }).notNull().defaultNow();

export const company = pgTable('company', { companyId: id('company_id'), name: text('name').notNull(), timezone: text('timezone').notNull().default('UTC'), industry: text('industry'), createdAt: created(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() });
export const dataSource = pgTable('data_source', { sourceId: id('source_id'), companyId: tenant(), name: text('name').notNull(), sourceType: text('source_type').notNull(), connectionMethod: text('connection_method').notNull(), channel: text('channel'), status: text('status').notNull().default('NOT_CONFIGURED'), credentialsReference: text('credentials_reference'), configuration: jsonb('configuration').notNull().default({}), lastSyncAt: timestamp('last_sync_at', { withTimezone: true }), createdAt: created() }, t => ({ nameUnique: unique().on(t.companyId, t.name) }));
export const sourceFieldMapping = pgTable('source_field_mapping', { mappingId: id('mapping_id'), sourceId: uuid('source_id').notNull().references(() => dataSource.sourceId, { onDelete: 'cascade' }), sourceField: text('source_field').notNull(), semanticField: text('semantic_field').notNull(), required: boolean('required').notNull().default(false), conditional: boolean('conditional').notNull().default(false), validationStatus: text('validation_status').notNull().default('UNMAPPED'), createdAt: created() }, t => ({ mappingUnique: unique().on(t.sourceId, t.sourceField, t.semanticField) }));
export const ingestionBatch = pgTable('ingestion_batch', { batchId: id('batch_id'), companyId: tenant(), sourceId: uuid('source_id').notNull().references(() => dataSource.sourceId, { onDelete: 'cascade' }), status: text('status').notNull().default('RECEIVED'), receivedAt: timestamp('received_at', { withTimezone: true }).notNull().defaultNow(), completedAt: timestamp('completed_at', { withTimezone: true }), totalRecords: integer('total_records').notNull().default(0), validRecords: integer('valid_records').notNull().default(0), invalidRecords: integer('invalid_records').notNull().default(0), errors: jsonb('errors').notNull().default([]) });
export const customer = pgTable('customer', { customerId: id('c_id'), companyId: tenant(), displayName: text('display_name'), createdAt: created() }, t => ({ tenantId: unique().on(t.companyId, t.customerId) }));
export const identityMapping = pgTable('identity_mapping', { mappingId: id('mapping_id'), companyId: tenant(), sourceId: uuid('source_id').references(() => dataSource.sourceId, { onDelete: 'cascade' }), identifierType: text('identifier_type').notNull(), identifierValue: text('identifier_value').notNull(), customerId: uuid('c_id').notNull().references(() => customer.customerId, { onDelete: 'cascade' }), validFrom: timestamp('valid_from', { withTimezone: true }), validTo: timestamp('valid_to', { withTimezone: true }), active: boolean('active').notNull().default(true), confidence: numeric('confidence', { precision: 5, scale: 4 }).notNull().default('1') }, t => ({ identityUnique: unique().on(t.companyId, t.sourceId, t.identifierType, t.identifierValue) }));
export const customerEntityLink = pgTable('customer_entity_link', { linkId: id('link_id'), companyId: tenant(), customerId: uuid('c_id').notNull().references(() => customer.customerId, { onDelete: 'cascade' }), entityType: text('entity_type').notNull(), entityId: text('entity_id').notNull(), validFrom: timestamp('valid_from', { withTimezone: true }), validTo: timestamp('valid_to', { withTimezone: true }) }, t => ({ linkUnique: unique().on(t.companyId, t.entityType, t.entityId, t.customerId) }));
export const event = pgTable('event', { eventId: id('event_id'), companyId: tenant(), sourceId: uuid('source_id').notNull().references(() => dataSource.sourceId, { onDelete: 'cascade' }), sourceEventId: text('source_event_id'), eventFingerprint: text('event_fingerprint'), customerId: uuid('c_id').references(() => customer.customerId), eventTime: timestamp('event_time', { withTimezone: true }), ingestedAt: timestamp('ingested_at', { withTimezone: true }).notNull().defaultNow(), processedAt: timestamp('processed_at', { withTimezone: true }), channel: text('channel'), eventType: text('event_type'), businessEntityType: text('business_entity_type'), businessEntityId: text('business_entity_id'), sessionId: text('session_id'), attributes: jsonb('attributes').notNull().default({}), rawPayload: jsonb('raw_payload').notNull().default({}) });
export const identityResolution = pgTable('identity_resolution', { resolutionId: id('resolution_id'), companyId: tenant(), eventId: uuid('event_id').references(() => event.eventId, { onDelete: 'cascade' }), customerId: uuid('c_id').references(() => customer.customerId), status: text('status').notNull(), method: text('method').notNull(), confidence: numeric('confidence', { precision: 5, scale: 4 }), evidence: jsonb('evidence').notNull().default({}), decidedAt: timestamp('decided_at', { withTimezone: true }).notNull().defaultNow() });
export const journeyDefinition = pgTable('journey_definition', { journeyId: id('journey_id'), companyId: tenant(), name: text('name').notNull(), status: text('status').notNull().default('DRAFT'), configuration: jsonb('configuration').notNull().default({}), createdAt: created() }, t => ({ nameUnique: unique().on(t.companyId, t.name) }));
export const journeyStageDefinition = pgTable('journey_stage_definition', { stageId: id('stage_id'), journeyId: uuid('journey_id').notNull().references(() => journeyDefinition.journeyId, { onDelete: 'cascade' }), stageKey: text('stage_key').notNull(), name: text('name').notNull(), ordinal: integer('ordinal').notNull(), required: boolean('required').notNull().default(true), timeoutSeconds: integer('timeout_seconds') }, t => ({ stageUnique: unique().on(t.journeyId, t.stageKey) }));
export const journeyEventMapping = pgTable('journey_event_mapping', { mappingId: id('mapping_id'), stageId: uuid('stage_id').notNull().references(() => journeyStageDefinition.stageId, { onDelete: 'cascade' }), eventType: text('event_type').notNull(), conditions: jsonb('conditions').notNull().default({}) }, t => ({ eventUnique: unique().on(t.stageId, t.eventType) }));
export const journeyInstance = pgTable('journey_instance', { instanceId: id('instance_id'), companyId: tenant(), journeyId: uuid('journey_id').notNull().references(() => journeyDefinition.journeyId, { onDelete: 'cascade' }), customerId: uuid('c_id').references(() => customer.customerId), entityType: text('entity_type'), entityId: text('entity_id'), status: text('status').notNull().default('ACTIVE'), startedAt: timestamp('started_at', { withTimezone: true }), completedAt: timestamp('completed_at', { withTimezone: true }), droppedOffAt: timestamp('dropped_off_at', { withTimezone: true }), dropoffStageId: uuid('dropoff_stage_id').references(() => journeyStageDefinition.stageId) });
export const journeyInstanceStage = pgTable('journey_instance_stage', { instanceStageId: id('instance_stage_id'), instanceId: uuid('instance_id').notNull().references(() => journeyInstance.instanceId, { onDelete: 'cascade' }), stageId: uuid('stage_id').notNull().references(() => journeyStageDefinition.stageId, { onDelete: 'cascade' }), status: text('status').notNull().default('NOT_REACHED'), reachedAt: timestamp('reached_at', { withTimezone: true }), completedAt: timestamp('completed_at', { withTimezone: true }) }, t => ({ stageUnique: unique().on(t.instanceId, t.stageId) }));
export const issue = pgTable('issue', { issueId: id('issue_id'), companyId: tenant(), customerId: uuid('c_id').references(() => customer.customerId), topic: text('topic'), status: text('status').notNull().default('OPEN'), createdAt: created(), lastContactAt: timestamp('last_contact_at', { withTimezone: true }), resolvedAt: timestamp('resolved_at', { withTimezone: true }), resolutionNote: text('resolution_note'), configuration: jsonb('configuration').notNull().default({}) });
export const complaint = pgTable('complaint', { complaintId: id('complaint_id'), companyId: tenant(), issueId: uuid('issue_id').references(() => issue.issueId, { onDelete: 'set null' }), customerId: uuid('c_id').references(() => customer.customerId), eventId: uuid('event_id').references(() => event.eventId, { onDelete: 'set null' }), topic: text('topic'), occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull(), channel: text('channel') });
export const escalation = pgTable('escalation', { escalationId: id('escalation_id'), companyId: tenant(), customerId: uuid('c_id').references(() => customer.customerId), issueId: uuid('issue_id').references(() => issue.issueId, { onDelete: 'set null' }), eventId: uuid('event_id').references(() => event.eventId, { onDelete: 'set null' }), detectionMethod: text('detection_method').notNull(), confidence: numeric('confidence', { precision: 5, scale: 4 }), evidence: jsonb('evidence').notNull().default({}), occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull() });
export const churnOutcome = pgTable('churn_outcome', { churnId: id('churn_id'), companyId: tenant(), customerId: uuid('c_id').notNull().references(() => customer.customerId, { onDelete: 'cascade' }), churnType: text('churn_type').notNull(), churnTimestamp: timestamp('churn_timestamp', { withTimezone: true }).notNull(), source: text('source').notNull(), sourceReference: text('source_reference'), recordedReason: text('recorded_reason') }, t => ({ churnUnique: unique().on(t.companyId, t.customerId, t.churnType, t.churnTimestamp, t.source) }));
export const issueGroupingRule = pgTable('issue_grouping_rule', { ruleId: id('rule_id'), companyId: tenant(), name: text('name').notNull(), configuration: jsonb('configuration').notNull().default({}), active: boolean('active').notNull().default(true) }, t => ({ nameUnique: unique().on(t.companyId, t.name) }));
export const reportDefinition = pgTable('report_definition', { reportId: id('report_id'), companyId: tenant(), name: text('name').notNull(), description: text('description'), reportType: text('report_type').notNull(), configuration: jsonb('configuration').notNull().default({}), createdBy: uuid('created_by'), isDefault: boolean('is_default').notNull().default(false), createdAt: created(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() });
export const reportRun = pgTable('report_run', { runId: id('run_id'), reportId: uuid('report_id').references(() => reportDefinition.reportId, { onDelete: 'set null' }), startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(), completedAt: timestamp('completed_at', { withTimezone: true }), status: text('status').notNull().default('REQUESTED'), parameters: jsonb('parameters').notNull().default({}), resultSnapshot: jsonb('result_snapshot'), artifactReference: jsonb('artifact_reference'), createdAt: created() });

export const domainTables = { company, dataSource, sourceFieldMapping, ingestionBatch, customer, identityMapping, customerEntityLink, event, identityResolution, journeyDefinition, journeyStageDefinition, journeyEventMapping, journeyInstance, journeyInstanceStage, issue, complaint, escalation, churnOutcome, issueGroupingRule, reportDefinition, reportRun };
